### ISSUE TITLE
@todo's with special characters are ignored

### ISSUE THREAD

**Issue by ItsPugle** [JasonEtco/todo#71] opened 2017-10-24 05:47 UTC
I've just tried creating a todo in a private repo under a new branch and it doesn't seem to be creating new issues like it used to on master.

**Comment by JasonEtco** [comment] 2017-10-24 05:50
@ItsPugle I've made some recent changes that make it work differently in PRs, and I'm guessing that's the cause.

I think what you're experiencing is that it won't create new issues from branches that aren't master, because it expects them to be in a PR and will write a comment instead. This means that commits made to a branch (but not a branch that has an open PR) won't do anything, which is not a good thing.

Thanks for letting me know, I'll get it fixed as soon as I can!

**Comment by ItsPugle** [comment] 2017-10-24 06:01
Ah that explains it, @JasonEtco! Thanks for getting on to this so quickly, by the way :)
Is their anyway to trigger todo to rescan the repository for the issue flags? Also, if I add a issue flag, like:
```
<!--
@todo Create Issue
@body Body
-->
```

Will it create a new issue if I commit this file again without removing the todo, or does it somehow keep track of which todos have already been made into an issue?

**Comment by JasonEtco** [comment] 2017-10-24 06:06
Here's how it all works:

It scans the commits made in a push. It reads the files changed or added in those commits, parses out the issues to generate, checks if they already exist (to prevent duplicates), then generates them. It works pretty similarly in a PR, but it makes comments instead of issues.

So to answer your two questions:

1. To trigger **todo**, just push changes to the files you want it to scan.
1. It will not create a new issue if the same one (based on the issue title and the file its in) already exists. If one does exist and is closed, it'll be reopened. If its already an open issue, nothing will happen :)

**Comment by ItsPugle** [comment] 2017-10-24 11:52
Ah sweeto! Do you mind letting me know when it's fixed so I can run a commit to rescan?

**Comment by JasonEtco** [comment] 2017-10-24 13:46
@ItsPugle when its fixed I'll close this issue 👍

**Comment by JasonEtco** [comment] 2017-10-24 16:24
@ItsPugle I've done some testing around, and my original thought on the branch issue doesn't seem to be the cause of the problem. I was able to push a file to a new branch without it being in a PR, and the issue was generated as expected.

Would you be able to copy-paste some of the relevant code in your file, and your configuration file for **todo** (if you have one)? It might be something in there that's causing this.

**Comment by ItsPugle** [comment] 2017-10-25 04:51
@JasonEtco I can just add you to the repository, if you're okay with that? Of course, I 100% expect you to keep any documents and files you view under strict confidentiality.

**Comment by JasonEtco** [comment] 2017-10-25 13:17
@ItsPugle I appreciate the offer, but I don't feel comfortable agreeing to confidentiality for something I know nothing about. It would be easier to just post the relevant bits of your code (just the `todo` comment and its surrounding lines). I'm guessing its something related to that; I've looked through my logs and there are no errors, so I'm guessing there's something in the title of your `todo` that's throwing it off.

Does it have any special characters (+!;'?"\|/[]{}()@#$%^&*)?

**Comment by ItsPugle** [comment] 2017-10-25 22:21
That's 100% a-ok :) Here's the involved code:

```markdown
## Present
<!-- 
@todo Can @AskRockStars and Spotify Community be combined?
--> 
\> Rising Star for [@AskRockStars](https://twitter.com/AskRockStars/)  
```

```markdown
## Gaming
<!-- 
@todo Decide on what I'm going to write here
@body Should I write an overview (not a list item), or a list of all things?
-->
\> {item}
```

This todo worked though, from an earlier commit:
```yaml
description: ItsPugle
# @todo Create Google Analytics Code
# @body Get in touch with Google Support about "Permission Denied" thing
google_analytics: [Your Google Analytics tracking ID]
```

**Comment by ItsPugle** [comment] 2017-10-26 23:11
I just pushed a change that added two spaces to the end of the second example:
```markdown
## Gaming
<!-- 
@todo Decide on what I'm going to write here
@body Should I write an overview (not a list item), or a list of all things?
-->
\> {item}  
```
and todo created an issue for it, but not the other todo that didn't work.

![screenshot 2017-10-27 at 9 08 34 am](https://user-images.githubusercontent.com/22669894/32081078-a5927e2c-baf6-11e7-8565-109aaac0cde2.png)
![screenshot 2017-10-27 at 9 10 24 am](https://user-images.githubusercontent.com/22669894/32081112-ccb78bd2-baf6-11e7-9db4-60003780b549.png)

**Comment by JasonEtco** [comment] 2017-10-26 23:18
Oh interesting; that means its very likely the `@` symbol in your other todo. I haven't had a chance to fix this yet, but now I have a good place to start, thanks @ItsPugle ! 👍

**Comment by ItsPugle** [comment] 2017-10-26 23:18
Happy to help! Let me know if you want me to test/try something out for you :)

**Comment by JasonEtco** [comment] 2017-10-26 23:53
Just wrote a quick test case and the whole special characters thing was it! I'll close this via a PR, thanks for debugging it with me ❤️

**Comment by ItsPugle** [comment] 2017-10-27 01:09
Ah okay! That's great that you could find the issue! 
Let me know when you push the patch!

**Comment by JasonEtco** [comment] 2017-11-01 13:11
@ItsPugle this *still* isn't the reason for your non-existant todo. I wrote a test in #73 and it passes; I even tried giving it your specific title. Basically, I'm stumped. I'm going to close this out since I can't reproduce it, but if you see it again let me know.

**Closed by JasonEtco** 2017-11-01 13:11 UTC
Labels: bug

**Comment by ItsPugle** [comment] 2017-11-01 22:40
God damn this is confusing lol
I'll ping you if this comes back :)
