### ISSUE TITLE
Allow creating issue on any branch (other than default one)

### ISSUE THREAD

**Issue by bendtherules** [JasonEtco/todo#145] opened 2018-06-12 08:30 UTC
Pushing a commit in a feature (on any non-master) branch currently doesn't seem to create a corresponding issue. There is also no option to enable this.

It will be nice to allow doing this, either by default or by changing an option.

**Comment by JasonEtco** [comment] 2018-06-12 11:34
Thanks @bendtherules - this is a duplicate of #128.

**Closed by JasonEtco** 2018-06-12 11:34 UTC
