### ISSUE TITLE
[BUG] Issues are not created

### ISSUE THREAD

**Issue by Vehmloewff** [JasonEtco/todo#239] opened 2019-12-13 00:16 UTC
Thanks for such a great product @JasonEtco!  I am looking forward to getting it to work correctly.

**Describe the bug**
I pushed [this commit](https://github.com/Vehmloewff/driza/commit/411d90bf9515a778d7cccc5311692b68f04b2120.diff) to master, but no issues were created.

This has happened a few times recently, where PRs have been merged, commits have been pushed, and no issues were created.

**To Reproduce**
I feel like this is more just a problem with my configuration, but if it is not, creating a `TODO` comment, committing it, and pushing it to master will do.

**Expected behavior**
I expect it to create an issue, but it doesn't.

**Additional information**
You can view the repo [here](https://github.com/Vehmloewff/driza).

**Comment by Mrgove10** [comment] 2020-01-10 20:13
Same issue here

**Comment by afcuttin** [comment] 2020-01-11 16:45
I also have this issue: no issue is created when I push the code to my repo

**Comment by C-Fergus** [comment] 2020-01-15 16:24
Same issue here. Pushes aren't creating issues.

**Comment by JasonEtco** [comment] 2020-01-15 17:56
Thanks for the patience folks. I'm not sure what changed, but I can confirm that this is reproducible. I've updated a bunch of dependencies and done some testing in #244 - seems to be working fine, and jumping back to `master` does not.

I've deployed #244, I'll be leaving it running for a little to make sure its 👌 and then I'll close this once it merges. Would love y'alls help verifying the fix if you have a chance 🙏

**Comment by C-Fergus** [comment] 2020-01-15 18:21
Sorry to be so daft Jason but I can't figure out how to do it for an application. If I clone the repository can I install it as an application on my own Github?

**Comment by JasonEtco** [comment] 2020-01-15 18:29
@C-Fergus you can install the app on a repository by going here: https://github.com/apps/todo and hitting the "Install" button on the right (it'll be "Configure" if you've already installed it somewhere)

**Comment by C-Fergus** [comment] 2020-01-15 18:33
@JasonEtco Ah I thought I would have to separately install the pull request. In that case it is still not creating issues with new pushes for me.

**Comment by JasonEtco** [comment] 2020-01-15 18:35
I've had to redeploy the PR a couple of times - can you try another push? It's working for me consistently now.

**Comment by C-Fergus** [comment] 2020-01-15 18:39
@JasonEtco It is still not creating issues. I may not be the best person to verify as I'm new to Github so I'm not sure if I'm testing it correctly. I have tried creating a new file and and editing an existing one, and then the same with a push from Github Desktop.

**Comment by JasonEtco** [comment] 2020-01-15 18:52
I've narrowed it down to a difference in the keyword used; `// TODO: ...` works fine, `/* @todo ...` does not. I'm guessing this was a regression introduced in https://github.com/JasonEtco/todo/pull/242 - I've added a test for it locally and I'll get that fixed. In the meantime, you should be able to use `TODO/todo` without the preceding `@`!

**Comment by C-Fergus** [comment] 2020-01-15 19:05
Ah yes, capitalised TODO works, although custom keywords also do not work.

**Comment by afcuttin** [comment] 2020-01-15 19:05
I've removed and reinstalled the app.
I'm not able to create a new issue

Will try again later

Il mer 15 gen 2020, 19:35 Jason Etcovitch <notifications@github.com> ha
scritto:

**Comment by afcuttin** [comment] 2020-01-15 19:06
Indeed I used @todo.
Later I'll try the other keyword

Il mer 15 gen 2020, 19:52 Jason Etcovitch <notifications@github.com> ha
scritto:

**Comment by afcuttin** [comment] 2020-01-15 22:32
> Edit: should be fixed now, made a change over in #244. I've tried it out and it seems to be working correctly now!

Yes, I confirm that it looks like it is fixed: https://github.com/afcuttin/todo-test

**Comment by JasonEtco** [comment] 2020-01-16 03:31
Thanks all for the feedback and patience ❤️ I've merged #244 and added some additional tests for specific cases that were causing problems. I'm going to go ahead and close this issue because I believe its solved - if you're still experiencing problems, please open a new issue with some of your own specific details. Thanks! ✨

**Closed by JasonEtco** 2020-01-16 03:31 UTC
Labels: bug
