### ISSUE TITLE
Duplicate comments in PRs

### ISSUE THREAD

**Issue by Seluj78** [JasonEtco/todo#159] opened 2018-09-27 15:50 UTC
Hi there !

I'm still getting duplicate comments/issues when pushing commits

see:
https://github.com/Seluj78/BYOSY-API/pull/2
https://github.com/Seluj78/BYOSY-API/pull/3

**Comment by Seluj78** [comment] 2018-09-27 15:53
Duh it's a private repo, let me replace that with screenshots

**Comment by Seluj78** [comment] 2018-09-27 15:53
![screenshot-2018-9-27 added first model user along with basic api routes for it by seluj78 pull request 2 seluj78 byo](https://user-images.githubusercontent.com/4641317/46158507-49863480-c27e-11e8-939c-8dcfcb7d6576.png)
![screenshot-2018-9-27 comments base api and model by seluj78 pull request 3 seluj78 byosy-api](https://user-images.githubusercontent.com/4641317/46158508-49863480-c27e-11e8-9e76-061ccc656781.png)

**Comment by JasonEtco** [comment] 2018-09-27 18:16
Duplicate of #120

**Closed by JasonEtco** 2018-09-27 18:16 UTC
Labels: bug, good first issue

**Comment by Seluj78** [comment] 2018-09-27 18:18
Forgot about that one, sorry @JasonEtco

**Comment by JasonEtco** [comment] 2018-09-27 18:18
No worries!
