### ISSUE TITLE
Line numbers are off

### ISSUE THREAD

**Issue by unional** [JasonEtco/todo#138] opened 2018-04-23 02:42 UTC
e.g.: 
https://github.com/unional/komondor/pull/122#issuecomment-383438326

while it should have been:
https://github.com/unional/komondor/blob/dbe3eb436d5022674dea23227cd5c31f4693a092/src/ActionTracker.ts#L49-L52

**Comment by JasonEtco** [comment] 2018-04-23 02:45
Thanks for the report - this is a duplicate of #131

**Closed by JasonEtco** 2018-04-23 02:45 UTC
